import type { QuickFillProduct } from '@/types/pantry';

export const QUICK_FILL_PRODUCTS: QuickFillProduct[] = [
  { id: 1,  name: 'Sal',               emoji: '🧂', unit: 'gramos',    category: 'Abarrotes' },
  { id: 2,  name: 'Aceite',            emoji: '🫒', unit: 'litros',    category: 'Abarrotes' },
  { id: 3,  name: 'Arroz',             emoji: '🍚', unit: 'kilos',     category: 'Abarrotes' },
  { id: 4,  name: 'Fideos',            emoji: '🍝', unit: 'paquetes',  category: 'Abarrotes' },
  { id: 5,  name: 'Cebolla',           emoji: '🧅', unit: 'unidades',  category: 'Verduras' },
  { id: 6,  name: 'Ajo',               emoji: '🧄', unit: 'cabezas',   category: 'Verduras' },
  { id: 7,  name: 'Papa',              emoji: '🥔', unit: 'kilos',     category: 'Verduras' },
  { id: 8,  name: 'Tomate',            emoji: '🍅', unit: 'kilos',     category: 'Verduras' },
  { id: 9,  name: 'Huevos',            emoji: '🥚', unit: 'unidades',  category: 'Lácteos/Frescos' },
  { id: 10, name: 'Leche',             emoji: '🥛', unit: 'litros',    category: 'Lácteos/Frescos' },
  { id: 11, name: 'Mantequilla',       emoji: '🧈', unit: 'unidades',  category: 'Lácteos/Frescos' },
  { id: 12, name: 'Queso',             emoji: '🧀', unit: 'unidades',  category: 'Lácteos/Frescos' },
  { id: 13, name: 'Pan',               emoji: '🍞', unit: 'unidades',  category: 'Panadería' },
  { id: 14, name: 'Café',              emoji: '☕', unit: 'unidades',  category: 'Abarrotes' },
  { id: 15, name: 'Té',                emoji: '🫖', unit: 'cajas',     category: 'Abarrotes' },
  { id: 16, name: 'Azúcar',            emoji: '🍬', unit: 'kilos',     category: 'Abarrotes' },
  { id: 17, name: 'Tomate en lata',    emoji: '🫙', unit: 'latas',     category: 'Abarrotes' },
  { id: 18, name: 'Porotos',           emoji: '🫘', unit: 'kilos',     category: 'Abarrotes' },
  { id: 19, name: 'Lentejas',          emoji: '🌽', unit: 'kilos',     category: 'Abarrotes' },
  { id: 20, name: 'Pechuga de pollo',  emoji: '🍗', unit: 'kilos',     category: 'Carnes/Freezer' },
  { id: 21, name: 'Carne molida',      emoji: '🥩', unit: 'kilos',     category: 'Carnes/Freezer' },
  { id: 22, name: 'Atún en lata',      emoji: '🐟', unit: 'latas',     category: 'Abarrotes' },
  { id: 23, name: 'Merkén',            emoji: '🌶️', unit: 'unidades',  category: 'Especias' },
  { id: 24, name: 'Orégano',           emoji: '🌿', unit: 'unidades',  category: 'Especias' },
  { id: 25, name: 'Mayonesa',          emoji: '🫙', unit: 'unidades',  category: 'Salsas' },
  { id: 26, name: 'Ketchup',           emoji: '🍯', unit: 'unidades',  category: 'Salsas' },
  { id: 27, name: 'Jugo en caja',      emoji: '🧃', unit: 'unidades',  category: 'Bebidas' },
  { id: 28, name: 'Limón',             emoji: '🍋', unit: 'unidades',  category: 'Verduras' },
  { id: 29, name: 'Zanahoria',         emoji: '🥕', unit: 'kilos',     category: 'Verduras' },
  { id: 30, name: 'Harina',            emoji: '🫙', unit: 'kilos',     category: 'Abarrotes' },
];
